on:
  push:
    branches: [master, ci]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: suisei-cn/actions-download-file@v1
        with:
          url: "https://github.com/HearthSim/Hearthstone-Deck-Tracker/releases/download/v1.16.10/Hearthstone.Deck.Tracker-v1.16.10.zip"

      - name: extract HDT
        run: 7z x Hearthstone.Deck.Tracker-v1.16.10.zip

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - run: dotnet build -c Release

      - name: squish all DLLs into one
        run: packages\LibZ.Tool.1.2.0.0\tools\libz.exe inject-dll --assembly bin\Release\RecorderPlugin.dll --include bin\Release\*.dll --exclude bin\Release\RecorderPlugin.dll .\RecorderPlugin.dll

      - name: upload built DLL
        uses: actions/upload-artifact@v2
        with:
          name: RecorderPlugin.dll
          path: .\RecorderPlugin.dll